spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financetracker
    username: fintrack
    password: fintrack
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate    # check schema against Flyway migrations
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug   # show SQL in logs (optional, helps debugging)